export const GET_PRODUCTS_REQUEST = "ADD_TO_CART";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "ADD_TO_CART";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";